# Generated by Django 4.2.6 on 2023-10-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(max_length=24)),
                ('transaction_type', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=24)),
                ('quantity', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('price_status', models.CharField(max_length=64)),
                ('fee', models.CharField(max_length=64)),
                ('date_time', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
